services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: restaurants
      POSTGRES_PASSWORD: postgres  # Replace with your desired password
    ports:
      - "5432:5432"

  rabbitmq.service:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   # Exposing RabbitMQ port
      - "15672:15672" # Exposing RabbitMQ management plugin UI port
